services:
  db:
    image: postgres:15
    volumes:
      - ./db:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    restart: "on-failure"
    ports:
      - "${DB_PORT}:5432"
