# Generated by Django 5.0.1 on 2024-01-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemlocation",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
