# Generated by Django 5.0.1 on 2024-02-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_itemlocation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemlocation',
            options={'ordering': ['id'], 'verbose_name': 'ItemLocation'},
        ),
    ]
