# Generated by Django 5.0.1 on 2024-02-05 22:27

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_alter_itemlocation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemlocation",
            options={"ordering": ["id"], "verbose_name": "Location"},
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors",
                        to="items.itemlocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("location_id"),
                name="unique_vendor_name",
            ),
        ),
    ]
