# Generated by Django 5.0.1 on 2024-02-05 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_itemlocation_unique_item_location_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="itemlocation",
            constraint=models.CheckConstraint(
                check=models.Q(("name", ""), _negated=True),
                name="non_empty_item_location_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.CheckConstraint(
                check=models.Q(("name", ""), _negated=True),
                name="non_empty_vendor_name",
            ),
        ),
    ]
