# Generated by Django 5.0.1 on 2024-02-06 15:51

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "items",
            "0009_rename_last_change_by_historicalvendor_last_modified_by_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="unique_order_name",
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("location_id"),
                models.F("date"),
                models.F("price"),
                models.F("quantity"),
                name="unique_order_name",
            ),
        ),
    ]
