# Generated by Django 5.0.1 on 2024-02-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0014_auto_20240209_1801"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="unique_order_name",
        ),
    ]
