# Generated by Django 5.0.1 on 2024-02-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "items",
            "0017_alter_historicalvendor_name_alter_itemlocation_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sale",
            name="unique_sale",
        ),
    ]
