# Generated by Django 5.0.2 on 2024-02-11 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_remove_sale_unique_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='positive_sale_debt',
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('debt__gte', 0)), name='positive_sale_debt', violation_error_message='Amount paid cannot be greater than potential revenue for this sale.'),
        ),
    ]
