# Generated by Django 5.0.1 on 2024-02-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0020_remove_vendor_unique_vendor_name"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE UNIQUE INDEX unique_case_insensitive_vendor_name ON items_vendor (LOWER(name), location_id);",
            "DROP INDEX unique_case_insensitive_vendor_name;",
        ),
    ]
