# Generated by Django 5.0.2 on 2024-02-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0021_auto_20240212_1440"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP INDEX unique_case_insensitive_name;"
            "CREATE UNIQUE INDEX unique_case_insensitive_name ON items_order (LOWER(name), location_id, date, price_per_item, quantity);",
        ),
    ]
