# Generated by Django 5.0.8 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0023_remove_sale_positive_sale_debt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvendor",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendor",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
