# Generated by Django 5.0.1 on 2024-02-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_useraccount_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraccount",
            options={"ordering": ["id"]},
        ),
    ]
