# Generated by Django 5.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_useraccount_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrictionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("order_create", "Create order"),
                            ("order_update", "Update order"),
                            ("sale_create", "Create sale"),
                            ("sale_update", "Update sale"),
                        ],
                        max_length=20,
                    ),
                ),
                ("route", models.CharField(max_length=255)),
                ("location_id", models.PositiveIntegerField(blank=True, null=True)),
                ("order_id", models.PositiveIntegerField(blank=True, null=True)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("error", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friction_events",
                        to="users.useraccount",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ProblemReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "friction_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_report",
                        to="users.frictionevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_reports",
                        to="users.useraccount",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
