# Generated by Django 5.0.8 on 2026-07-31 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_vendor_deleted'),
        ('users', '0005_assistantconversation_assistantdailyusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantconversation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_chats', to='items.itemlocation'),
        ),
    ]
