# Generated by Django 4.2.11 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_assistantconversation_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantmessage",
            name="error_message",
            field=models.TextField(blank=True),
        ),
    ]
