# Generated by Django 4.2.11 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_assistantmessage_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantmessage",
            name="client_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assistantmessage",
            name="user_agent",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
