name: CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/apps/inventorymanager
            eval $(ssh-agent -s) 1> /dev/null
            ssh-add -q ~/.ssh/github
            git pull origin main
            git status
            echo ${{ secrets.USER_PASS }} | sudo -S ./deploy.sh
